<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2018-09-17 15:59:31
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php /* @escapeNotVerified */ echo $selector?> magicproduct magiccategory autoplay">
<?php
$tabs = $this->getTabs();
$numTabs = count($tabs);
if($numTabs): ?>
    <div class="magic-category">
	    <div class="block-title-tabs clearfix wow fadeInUp" data-wow-delay="0.5s" data-wow-duration="1.5s">
		    <h3 class="title"><?php echo __($this->getTitle()); ?></h3>
		    <span class="toggle-tab mobile" style="display:none"><i class="fa fa-bars"></i></span>
			<ul class="magictabs toggle-content clearfix" data-ajax ='<?php /* @escapeNotVerified */ echo $this->getAjaxCfg() ?>'>
			<?php $activated = $this->getTabActivated();
				$limit = $this->getLimit();
				$single = ($numTabs ==1) ? 'single' : '';
				foreach ($tabs as $type => $name):
					$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
					$status .= ($type == $activated) ? " activated $single" : '';
					/* @escapeNotVerified */ echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
				endforeach;
			?>
			</ul>
	    </div>
		<div class="cms-static-brand wow fadeInUp" data-wow-delay="0.5s" data-wow-duration="1.5s">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brand-home-8')->toHtml(); ?>
		</div>
	</div>
<?php endif ?>
	
	<div class="block-banner wow fadeInUp" data-wow-delay="0.9s" data-wow-duration="1.5s">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-image-home-8')->toHtml(); ?>
	</div>
	<div class="box-product-content clearfix wow fadeInUp" data-wow-delay="1.3s" data-wow-duration="1.5s">
	    <?php if($image = $this->getData('image') ) : ?>
	    <?php $_category = $this->getCategory() ?>
	    <div class="box-product-adv">
			<div class="promotion">
				<a href="<?php echo $_category->getUrl() ?>"><img src="<?php /* @escapeNotVerified */ echo $this->getImage($image);?>"></a>
			</div>
	    </div> 
		<?php endif ?>
		
	    <div class="box-product">
		<div class="ajax_loading" style="display:none" data-url="<?php /* @escapeNotVerified */ echo $this->getUrl('magicproduct/index/category', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
			<div class="content-products" 
			<?php foreach ($this->getFrontendCfg() as $opt) :?>
				data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
			<?php endforeach;?>        
			>
			<?php 
				$timer = $this->getTimer();
				if($timer) echo $this->getContent('category/gridtimer.phtml');	
				else echo $this->getContent('category/grid.phtml');	
			?>
			</div>
			
		</div>
	</div>	
</div>