<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magiccart\Alothemes\Block\Recent\Order
 */
?>
<?php $selector = 'alo-content-'. uniqid(); ?>
<div class= "<?php /* @escapeNotVerified */ echo $selector?> recentorder suggest-slider autoplay"
		data-autoplay="<?php echo $this->getWidgetCfg('autoplay') ?>" 
		data-firsttime="<?php echo $this->getWidgetCfg('firsttime') ?>" 
		data-speed="<?php echo $this->getWidgetCfg('speed') ?>"
	>
	<div class="notify-slider-wrapper content-products"       
	>
		<?php
		$_productCollection = $block->getLoadedProductCollection();
		$_helper = $this->helper('Magento\Catalog\Helper\Output');
		$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
		?>
		
		<div class="mage-magictabs mc-<?php echo $this->escapeHtml($this->getTypeFilter());?> activated">
		<?php if (!$_productCollection->count()): ?>
		    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
		<?php else: ?>
		    <?php
		        $viewMode = 'grid';
		        /*
		        $image = 'category_page_grid';
		        $image = 'product_page_image_small';
		        */
		        $image = 'mini_cart_product_thumbnail';
		        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		    /**
		     * Position for actions regarding image size changing in vde if needed
		     */
		    $pos = $block->getPositioned();
		    ?>
		    <?php 
		        $showCart       = 1;
		        $showCompare    = 1;
		        $showWishlist   = 1;
		        $showReview     = 1;
		        $showQuickview  = 1;
		    ?>
		    <div class="notify-slider products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
		        <?php $iterator = 1; ?>
		        <ul class="slider products list items product-items">
		            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
		            <?php foreach ($_productCollection as $_product): ?>
		                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
		                <div class="product-item-info" data-container="product-grid">
		                    <?php
		                    $productImage = $block->getImage($_product, $image);
		                    if ($pos != null) {
		                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
		                            . 'top:' . $productImage->getHeight() . 'px;"';
		                    }
		                    ?>
		                    <?php // Product Image ?>
		                    <div class="images-container">
		                        <div class="product-hover">
								    <?php $product_label = $_aloHelper->getLabels($_product); 
			                            if($product_label) :
										?>
										<div class="product-label-2">
			                            <div class="product-label">
			                                <?php echo $product_label; ?>
			                            </div>
										</div>
									<?php endif ?>
		                            <?php //echo $_aloHelper->getTimer($_product); ?>
		                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
		                                <?php echo $productImage->toHtml(); ?>
		                            </a>
		                            
		                        </div>
		                    </div>
		                    <div class="product details product-item-details products-textlink clearfix">
		                    	<div class="someone-purchased"><?php echo __('Someone purchased a')?></div>
		                        <?php
		                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
		                        ?>
		                        <h2 class="product-name product-item-name">
		                            <a class="product-item-link"
		                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
		                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
		                            </a>
		                        </h2>
		                        <?php 
		                        	$info = $this->getInfoPurchased($_product);
		                        	if($info) :
		                         ?>
			                        <span class="time-purchased"><?php echo $this->getInfoTime($info['time']) ?></span>
			                        <span class="address-purchased"><?php echo $info['address'] ?></span>
			                    <?php endif; ?>
		                        <?php echo $showReview ? $block->getReviewsSummaryHtml($_product, $templateType) : ''; ?>
		                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
		                        <?php echo $block->getProductDetailsHtml($_product); ?>
		                    </div>
		                    <?php if ($showQuickview): ?>
                            	<div class="link-view">
                            		<button type="button" class="quickview <?php echo $_product->getTypeId() ?>"  title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url:'<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure'=>$this->getRequest()->isSecure()) ) ?>'});"><span><?php echo __('Quick view') ?></span>
                            		</button>
                            	</div>
                            <?php endif; ?>
                            <span class="x-close"><?php echo __('Close') ?></span>
		                </div>
		                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
		            <?php endforeach; ?>
		        </ul>
		    </div>
		    <?php // echo $block->getToolbarHtml() ?>
		    <?php if (!$block->isRedirectToCartEnabled()) : ?>
		        <script type="text/x-magento-init">
		        {
		            "[data-role=tocart-form], .form.map.checkout": {
		                "catalogAddToCart": {}
		            }
		        }
		        </script>
		    <?php endif; ?>
		<?php endif; ?>
		</div>
	</div>
</div>