<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */


?>
<div class="footer-bottom">
	<div class="main1 row">
		
		<div class="footer-bottom__left">
			<span class="copyright">
				<?php /* @escapeNotVerified */ echo preg_replace('/yyyy/', date('Y'), $block->getCopyright()); ?>&nbsp;
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('coppyright')->toHtml(); ?>
			</span>
		</div>
		<div class="footer-center">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-footer-bottom-home5')->toHtml(); ?>
		</div>
		<div class="footer-bottom__right">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('payment')->toHtml(); ?>
		</div>
	</div>
	<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span class="back-to-top"><?php echo __('Back to Top')?></span></a>
	

</div>